set -g @color-primary "red"
set -g @color-default "default"
set -g @color-zoomed "yellow"
set -g @color-bell "red"

set -g status-justify absolute-centre
set -g status-style "bg=#{@color-default},fg=#{@color-default},bold"

set -g status-left " #{?client_prefix,,} #{?#{!=:#{client_key_table},root},· #{client_key_table},}"
set -g status-left-style "fg=#{@color-primary},bg=#{@color-default}"
set -g status-left-length 40

set -g status-right "session: #S · #(date "+%H:%M") "
set -g status-right-style "fg=#{@color-primary}"
set -g status-right-length 40

set -g window-status-format "#W "
set -g window-status-current-format "#W "
set -g window-status-current-style "#{?window_zoomed_flag,fg=#{@color-zoomed},fg=#{@color-primary}}"
set -g window-status-bell-style "fg=#{@color-bell}"

# vim:ft=tmux
