# Set $TERM
set -g default-terminal "tmux-256color"
# Enable true RGB
set -g terminal-overrides "*:RGB"
# Copy mode uses copy-mode-vi key table (vi keymaps)
set -g mode-keys vi
# Copy mode should use system clipboard
set -g set-clipboard on
# Use this command if copy-pipe is used with no arguments
# wl-copy: -n means trim trailing newlines
set -g copy-command "wl-copy -n"

# Windows start at index 1
set -g base-index 1
# Panes start at index 1
set -g pane-base-index 1
# After a window closes, renumber the rest
set -g renumber-windows on

# Enable mouse support
set -g mouse on
# React to focus events
set -g focus-events on

# Scrollback history size
set -g history-limit 10000

# Set pane size to N when switching layout
set -g main-pane-height 50\%
set -g main-pane-width 50\%

# Update statusbar every N seconds
set -g status-interval 5
# Wait N ms before letting <Esc> key into pane process
set -g escape-time 0
# Wait N ms for repeatable keymaps
set -g repeat-time 500
# Statusbar messages are shown for N ms
set -g display-time 4000
# Pane numbers are shown for N ms
set -g display-panes-time 4000

# vim:ft=tmux
