set -g @TMUX_CONFIG_DIR "$HOME/.config/tmux/modules/"

source -F "#{@TMUX_CONFIG_DIR}/option.conf"
source -F "#{@TMUX_CONFIG_DIR}/appearance.conf"
source -F "#{@TMUX_CONFIG_DIR}/keymap.conf"
source -F "#{@TMUX_CONFIG_DIR}/plugin.conf"
